index:
    path: /
    defaults: { _controller: AppBundle:Main:index }

bio:
    path: /bio
    defaults: { _controller: AppBundle:Main:aboutUs }

contact:
    path: /contact
    defaults: { _controller: AppBundle:Main:contact }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

admin:
    path: /admin
    defaults: { _controller: AppBundle:Main:admin }

inbox:
    path: /admin/inbox
    defaults: { _controller: AppBundle:Main:inbox }

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

emails_json:
    path: /admin/emails_json
    defaults: { _controller: AppBundle:Main:getJsonEmails }

unread_email:
    path: /admin/unread_email
    defaults: { _controller: AppBundle:Main:unReadEmail }

read_email:
    path: /admin/read_email
    defaults: { _controller: AppBundle:Main:readEmail }

delete_email:
    path: /admin/delete_email
    defaults: { _controller: AppBundle:Main:deleteEmail }

unread_email_id:
    path: /admin/unread_email_id
    defaults: { _controller: AppBundle:Main:unreadEmailId }

read_email_id:
    path: /admin/read_email_id
    defaults: { _controller: AppBundle:Main:readEmailId }

delete_email_id:
    path: /admin/delete_email_id
    defaults: { _controller: AppBundle:Main:deleteEmailId }