index:
    path: /
    defaults: { _controller: AppBundle:Main:index }

bio:
    path: /bio
    defaults: { _controller: AppBundle:Main:aboutUs }

contact:
    path: /contact
    defaults: { _controller: AppBundle:Main:contact }

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

admin:
    path: /admin
    defaults: { _controller: AppBundle:Main:admin }

inbox:
    path: /admin/inbox
    defaults: { _controller: AppBundle:Main:inbox }

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

developer:
    path: /admin/developer
    defaults: { _controller: AppBundle:Admin:developer }

developers_json:
    path: /admin/developers_json
    defaults: { _controller: AppBundle:Admin:getJsonDeveloper }

save_developer:
    path: /admin/save_developer
    defaults: { _controller: AppBundle:Admin:saveDeveloper }