index:
    path: /
    defaults: { _controller: AppBundle:Main:index }

bio:
    path: /bio
    defaults: { _controller: AppBundle:Main:aboutUs }

contact:
    path: /contact
    defaults: { _controller: AppBundle:Main:contact }